STATUS_VALUES = [
    "EMPTY",
    "TOPIC_GENERATED",
    "SCRIPT_GENERATED",
    "WAITING_USER_SELECTION",
    "SELECTED",
    "ASSET_GENERATING",
    "ASSET_REVIEW",
    "VIDEO_RENDERING",
    "VIDEO_RENDERED",
    "IMAGE_CRAWLING",
    "IMAGE_CANDIDATES_READY",
    "IMAGE_SELECTED",
    "IMAGE_CRAWLING_FAILED",
    "WAITING_USER_APPROVAL",
    "WAITING_FINAL_APPROVAL",
    "FINAL_APPROVING",
    "FINAL_APPROVED",
    "APPROVED",
    "UPLOADING_PRIVATE",
    "UPLOADED_PRIVATE",
    "SCHEDULED",
    "PUBLISHED",
    "FAILED",
    "VIDEO_RENDER_FAILED",
    "CANCELLED",
]

ON_OFF_VALUES = ["ON", "OFF"]
TRUE_FALSE_VALUES = ["TRUE", "FALSE"]

VISUAL_STYLE_VALUES = [
    "따뜻한 수채화 애니메이션풍",
    "실사풍",
    "인포그래픽",
    "스틱맨",
    "밝고 부드러운 가족용 3D 애니메이션풍",
    "고품질 3D 캐릭터 애니메이션풍",
    "사용자 정의",
]

SHEET_NAMES = [
    "사용안내",
    "채널목록",
    "검수대기",
    "업로드현황",
    "_SYSTEM_JOBS",
    "_SYSTEM_LOGS",
    "_SYSTEM_ASSETS",
    "_SYSTEM_SESSIONS",
    "_SYSTEM_SETTINGS",
]

CHANNEL_LIST_COLUMNS = [
    "channel_id",
    "channel_name",
    "sheet_name",
    "automation_enabled",
    "google_account_email",
    "youtube_channel_id",
    "oauth_connected",
    "monday_enabled",
    "tuesday_enabled",
    "wednesday_enabled",
    "thursday_enabled",
    "friday_enabled",
    "saturday_enabled",
    "sunday_enabled",
    "upload_time",
    "default_video_length_minutes",
    "default_visual_style",
    "alert_phone_number",
    "last_topic_generated_week",
    "last_checked_at",
    "status",
    "error_message",
]

CHANNEL_LIST_LABELS = {
    "channel_id": "채널 ID",
    "channel_name": "채널명",
    "sheet_name": "시트명",
    "automation_enabled": "자동화",
    "google_account_email": "구글 계정 이메일",
    "youtube_channel_id": "유튜브 채널 ID",
    "oauth_connected": "OAuth 연결상태",
    "monday_enabled": "월요일 업로드",
    "tuesday_enabled": "화요일 업로드",
    "wednesday_enabled": "수요일 업로드",
    "thursday_enabled": "목요일 업로드",
    "friday_enabled": "금요일 업로드",
    "saturday_enabled": "토요일 업로드",
    "sunday_enabled": "일요일 업로드",
    "upload_time": "업로드 시간",
    "default_video_length_minutes": "기본 영상 길이(분)",
    "default_visual_style": "기본 그림체",
    "alert_phone_number": "알림 전화번호",
    "last_topic_generated_week": "마지막 소주제 생성 주차",
    "last_checked_at": "마지막 확인 시각",
    "status": "상태",
    "error_message": "오류 메시지",
}

CHANNEL_SETTINGS_KEYS = [
    "channel_name",
    "channel_description",
    "automation_enabled",
    "intro_format_prompt",
    "outro_format_prompt",
    "upload_days",
    "upload_time",
    "default_video_length_minutes",
    "target_age_group",
    "narration_style",
    "narration_speed",
    "subtitle_font",
    "subtitle_color",
    "subtitle_outline_color",
    "subtitle_position",
    "visual_style_default",
    "thumbnail_style_prompt",
    "caution_prompt",
    "alert_phone_number",
]

CHANNEL_SETTINGS_LABELS = {
    "channel_name": "채널명",
    "channel_description": "채널 설명",
    "automation_enabled": "자동화",
    "intro_format_prompt": "인트로 형식",
    "outro_format_prompt": "아웃트로 형식",
    "upload_days": "업로드 요일",
    "upload_time": "업로드 시간",
    "default_video_length_minutes": "기본 영상 길이(분)",
    "target_age_group": "대상 연령",
    "narration_style": "나레이션 스타일",
    "narration_speed": "나레이션 속도",
    "subtitle_font": "자막 글꼴",
    "subtitle_color": "자막 글자색",
    "subtitle_outline_color": "자막 테두리색",
    "subtitle_position": "자막 위치",
    "visual_style_default": "기본 그림체",
    "thumbnail_style_prompt": "썸네일 스타일",
    "caution_prompt": "주의사항",
    "alert_phone_number": "알림 전화번호",
}

CHANNEL_TOPIC_COLUMNS = [
    "topic_id",
    "week_key",
    "upload_day",
    "upload_datetime",
    "selected",
    "topic_title",
    "topic_type",
    "planning_note",
    "script_summary",
    "full_script",
    "video_length_minutes",
    "visual_style",
    "user_custom_style_prompt",
    "status",
    "review_link",
    "edit_session_link",
    "thumbnail_url",
    "rendered_video_url",
    "youtube_video_id",
    "youtube_private_url",
    "youtube_public_url",
    "error_message",
    "created_at",
    "updated_at",
]

CHANNEL_TOPIC_LABELS = {
    "topic_id": "소주제 ID",
    "week_key": "주차",
    "upload_day": "업로드 요일",
    "upload_datetime": "업로드 예정시각",
    "selected": "선택",
    "topic_title": "영상 제목",
    "topic_type": "주제 유형",
    "planning_note": "기획 의도",
    "script_summary": "대본 요약",
    "full_script": "전체 대본",
    "video_length_minutes": "영상 길이(분)",
    "visual_style": "그림체",
    "user_custom_style_prompt": "사용자 그림체 요청",
    "status": "상태",
    "review_link": "검수 링크",
    "edit_session_link": "편집 링크",
    "thumbnail_url": "썸네일 URL",
    "rendered_video_url": "완성 영상 URL",
    "youtube_video_id": "유튜브 영상 ID",
    "youtube_private_url": "비공개 영상 URL",
    "youtube_public_url": "공개 영상 URL",
    "error_message": "오류 메시지",
    "created_at": "생성 시각",
    "updated_at": "수정 시각",
}

REVIEW_COLUMNS = [
    "task_id",
    "channel_id",
    "channel_name",
    "topic_id",
    "task_type",
    "title",
    "status",
    "deadline",
    "review_link",
    "user_action",
    "updated_at",
]

REVIEW_LABELS = {
    "task_id": "작업 ID",
    "channel_id": "채널 ID",
    "channel_name": "채널명",
    "topic_id": "소주제 ID",
    "task_type": "작업 유형",
    "title": "제목",
    "status": "상태",
    "deadline": "마감일",
    "review_link": "검수 링크",
    "user_action": "사용자 요청",
    "updated_at": "수정 시각",
}

UPLOAD_COLUMNS = [
    "upload_id",
    "channel_id",
    "channel_name",
    "topic_id",
    "title",
    "upload_datetime",
    "publish_datetime",
    "status",
    "youtube_video_id",
    "youtube_private_url",
    "youtube_public_url",
    "error_message",
    "updated_at",
]

UPLOAD_LABELS = {
    "upload_id": "업로드 ID",
    "channel_id": "채널 ID",
    "channel_name": "채널명",
    "topic_id": "소주제 ID",
    "title": "제목",
    "upload_datetime": "업로드 시각",
    "publish_datetime": "공개 예정시각",
    "status": "상태",
    "youtube_video_id": "유튜브 영상 ID",
    "youtube_private_url": "비공개 영상 URL",
    "youtube_public_url": "공개 영상 URL",
    "error_message": "오류 메시지",
    "updated_at": "수정 시각",
}

VISIBLE_HEADER_LABELS = {
    **CHANNEL_LIST_LABELS,
    **CHANNEL_TOPIC_LABELS,
    **REVIEW_LABELS,
    **UPLOAD_LABELS,
}

HEADER_ALIASES = {label: key for key, label in VISIBLE_HEADER_LABELS.items()}

JOB_COLUMNS = [
    "job_id",
    "job_type",
    "channel_id",
    "topic_id",
    "status",
    "locked_by",
    "locked_until",
    "retry_count",
    "max_retries",
    "input_json",
    "output_json",
    "error_message",
    "created_at",
    "updated_at",
]

LOG_COLUMNS = [
    "log_id",
    "level",
    "job_id",
    "channel_id",
    "topic_id",
    "message",
    "created_at",
]

ASSET_COLUMNS = [
    "asset_id",
    "topic_id",
    "scene_id",
    "asset_type",
    "asset_url",
    "prompt",
    "source",
    "credit",
    "license",
    "status",
    "version",
    "created_at",
]

SESSION_COLUMNS = [
    "session_id",
    "topic_id",
    "edit_session_url",
    "current_render_version",
    "replacement_history_json",
    "created_at",
    "updated_at",
]
